### PR TITLE
Added more documentation for how to use Mangadex::Manga.list with present arguments

### PR DESCRIPTION
**Pull request by royalgiant**
References the problem with #52. 

I had trouble learning how to pass parameters into keyword arguments. Hope this little change in the docs/readme helps people who are looking to do the same thing (which I suspect they will).

@thedrummeraki please review and approve as appropriate.

### CODE REVIEW

**Comment by thedrummeraki** [comment]
Thanks for the PR! It looks cool, but I'm thinking that these docs should be a bit more general and less framework (Rails?) agnostic if possible.

Maybe something like:

```ruby
args = {
  available_translated_language: ['en', 'uk'],
  includes: [:cover_art, :author, :artist],
  title: title,
  included_tags: [tag].compact,
}
response = Mangadex::Manga.list(**args)
```

**Comment by thedrummeraki** [comment]
Following my suggestion above, have you taken a look at #51 and #55? With these merged, you should be able to do something like

```ruby
args = {
  available_translated_language: ['en', 'uk'],
  includes: [:cover_art, :author, :artist],
  title: params[:search],
  included_tags: [params[:tag]].compact,
}
response = Mangadex::Manga.list(**args)
```

If your app only accepts 1 tag, I would suggest:

```
args = {
  available_translated_language: ['en', 'uk'],
  includes: [:cover_art, :author, :artist],
  title: params[:search],
  included_tags: params[:tag],
}
response = Mangadex::Manga.list(**args)
```

**Comment by royalgiant** [comment]
@thedrummeraki crap. Alright, forget this PR then. I didn't look at the latest PR. I've been completely swamped with work, Youtube, and working on a deal for a sponsor on the side. You are completely right, I will check it out tomorrow. Didn't see you fixed the empty filter conditions until now. My bad! 👍

**Comment by royalgiant** [comment]
Just tested this change. You killed it, this was a stellar change.

Thanks man!

Donald Lee

Contact Number: +1 (205)835-3859
Connect with me on Linkedin: https://ca.linkedin.com/in/donaldlee50
Check me out at Github: https://github.com/royalgiant
Learn Personal Finance on my Youtube Channel:
https://youtube.com/coursehackclub

**Pull request closed without merging**
