### PR TITLE
Added Statistic Endpoint to Mangadex API

### PR DESCRIPTION
**Pull request by royalgiant**
Didn't actually do https://api.mangadex.org/docs/docs/statistics/#find-statistics-about-given-manga. That one's broken, try it on swagger: https://api.mangadex.org/docs/swagger.html#/

Test manga ids: 7dbc59db-6c77-4084-94ec-a38e0826faab and ce7cd7b0-e595-4f0d-98e8-447da10d652d

Try them individually, it works. Together, it doesn't. Mangadex needs to fix it.

Running the GET on statistics on console works though. Would appreciate it this can be reviewed, merged, and pushed if possible. I need to use statistics in my own project. Thanks!

### CODE REVIEW

**Comment by royalgiant** [comment]
@thedrummeraki any eyes on this? I'm not sure what process you set up and whether this is OK to merge.

Thank you,
Donald

**Comment by thedrummeraki** [comment]
Hey @royalgiant thanks for the ping, sorry I missed the email.

I'll take a look tonight after work. It looks like this returns a Hash instead of an object. Since you added properties to `Mangadex::Statistics`, I think it might be worth looking into how to make this a statistics object. I'll take a look when reviewing and testing tonight.

I don't have a good way to write tests for this yet, so it should be fine without any tests.

**Comment by royalgiant** [comment]
Thanks brother,

Feel free to alter or make changes/suggestions and I can do them. New to
how you write your API (good learning experience).

Thanks again for the API, it's very much appreciated.

Donald Lee

Contact Number: +1 (205)835-3859
Connect with me on Linkedin: https://ca.linkedin.com/in/donaldlee50
Check me out at Github: https://github.com/royalgiant
Learn Personal Finance on my Youtube Channel:
https://youtube.com/coursehackclub

**Review by thedrummeraki — APPROVED** [review]
Ok, so I think that not going the object route makes sense since Mangadex here doesn't tell it if it's an entity or a list, so return a hash should be fine. If we convert it to an object it might be too complicated.

Looking at this https://api.mangadex.org/docs/docs/statistics/#find-statistics-about-given-manga, it might be worth creating a new method for that. I'll open a PR and tag you on it with a solution

**Comment by thedrummeraki** [comment]
Thank you @royalgiant!

**Pull request merged**
